#!/bin/bash

branch="$(git rev-parse --abbrev-ref HEAD)"
protected_branches=("main")

# Get the list of affected files (local changes compared to remote)
affected_files=$(git diff --name-only origin/"$branch")

# Check if any of the affected files are in client or server folders
if echo "$affected_files" | grep -qE "^(client|server)/"; then
    for protected_branch in "${protected_branches[@]}"; do
        if [ "$branch" = "$protected_branch" ]; then
            echo "You cannot push changes to '$branch' for 'client/' or 'server/' files!"
            echo "Please open a Pull Request."
            exit 1
        fi
    done
fi

# Allow the push if no restricted changes
echo "Push allowed."
exit 0
